FROM docker.topicusonderwijs.nl/jboss/base-jdk:8

USER root

RUN groupadd --gid 10000 jenkins \
  && useradd --uid 10000 --gid jenkins --shell /bin/bash --create-home jenkins

# Install tooling, e.g. git
RUN yum install -y git && yum clean all
